version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
      # RABBITMQ_ERLANG_COOKIE: some-unique-cookie-string
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    # networks:
    #   - rabbitmq-network
    restart: always

volumes:
  rabbitmq-data:

    # networks:
    #   rabbitmq-network:
    #     driver: bridge
